export enum StrategyState {
    IDLE = 'IDLE',
    RANGE_DEFINED = 'RANGE_DEFINED',
    BREAKOUT_DETECTED = 'BREAKOUT_DETECTED',
    WAIT_PULLBACK = 'WAIT_PULLBACK',
    ENTRY_PLACED = 'ENTRY_PLACED',
    IN_POSITION = 'IN_POSITION',
    EXIT = 'EXIT',
    RESET = 'RESET'
}